[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pycam"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["pycam"]

[tool.setuptools.dynamic]
dependencies = {file = ['requirements.txt']}